env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
  PROVIDER_CATEGORY: ${{ github.event.client_payload.category }}
  PROVIDER_DISPLAY_NAME: ${{ github.event.client_payload.display-name }}
  PROVIDER_IS_COMPONENT: ${{ github.event.client_payload.is-component }}
  PROVIDER_NAME: ${{ github.event.client_payload.project }}
  PROVIDER_SCHEMA_PATH: ${{ github.event.client_payload.schema-path }}
  PROVIDER_SHORT_NAME: ${{ github.event.client_payload.project-shortname }}
  PROVIDER_PUBLISHER_NAME: ${{ github.event.client_payload.publisher }}
  PROVIDER_VERSION: ${{ github.event.client_payload.ref }}

name: Generate package API docs

on:
  repository_dispatch:

jobs:

  gen-api-docs:
    runs-on: ubuntu-18.04
    steps:
      - run: echo "Building ${{ env.PROVIDER_NAME }} docs @ ${{ env.PROVIDER_VERSION }}"
      - name: checkout registry repo
        uses: actions/checkout@v2
        with:
          repository: pulumi/registry
          path: registry

      - name: checkout pulumi repo
        uses: actions/checkout@v2
        with:
          repository: pulumi/pulumi
          path: pulumi

      - name: checkout tfgen provider
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repo }}
          ref: ${{ env.PROVIDER_VERSION }}
          path: ${{ env.PROVIDER_NAME }}
          token: ${{ env.GITHUB_TOKEN }}

      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.1.0
        with:
          repo: pulumi/pulumictl

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.82.0'
          extended: true

      - run: make ensure ensure_tools
        working-directory: registry

      - name: generate resource docs
        run: ./scripts/gen_resource_docs.sh "${{ env.PROVIDER_SHORT_NAME }}" true "${{ env.PROVIDER_VERSION }}" "${{ env.PROVIDER_SCHEMA_PATH }}"
        working-directory: registry

      - name: generate package metadata
        run: ./scripts/gen_package_metadata.sh "${{ env.PROVIDER_SHORT_NAME }}" "${{ env.PROVIDER_SCHEMA_PATH }}" "${{ env.PROVIDER_VERSION }}" "${{ env.PROVIDER_PUBLISHER_NAME }}" "${{ env.PROVIDER_DISPLAY_NAME }}" "${{ env.PROVIDER_CATEGORY }}" "${{ env.PROVIDER_IS_COMPONENT }}"
        working-directory: registry

      - name: git status
        run: git status && git diff
        working-directory: registry

      - name: Create registry PR
        uses: peter-evans/create-pull-request@v3
        with:
          path: registry
          token: ${{ secrets.PULUMI_BOT_TOKEN }}
          committer: Pulumi Bot <bot@pulumi.com>
          author: Pulumi Bot <bot@pulumi.com>
          commit-message: "Regenerate docs"
          labels: "automation/tfgen-provider-docs,automation/merge"
          title: "Regen metadata for ${{ env.PROVIDER_SHORT_NAME }}@${{ env.PROVIDER_VERSION }}"
          body: ""
          branch: "${{ env.PROVIDER_SHORT_NAME }}/${{ github.run_id }}-${{ github.run_number }}"
